# by default Travis uses JDK 8u31, which is much too old for Scala 2.12 (versions before 8u102 have issues - https://issues.scala-lang.org/browse/SI-9828)
dist: trusty
sudo: false

language: scala

scala:
  - 2.12.6
  - 2.11.12

jdk: oraclejdk8

script: sbt ++$TRAVIS_SCALA_VERSION clean test

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      secure: "q9lGIZs2AiaLJddpjJbePEL4PrOObvE5FpdIHGoOQGpMyBYj09mtqM+5pwrFR3QnCP8OM8QJBrpOeGm1Yy1gtzLhS8TKo7na0qlXVeukVOCWw3kAtpccyNcgwlD3EGyGTqxU2nMR3dLLN1A3Wntf5dx7X6stbXTKKhY1esXRgT3ckdK0qkGPWA1DU829qaVmsFdg+siP3aTil9hkl6R3HiosfIg5IJcAMsywjUfoXmd33KaM0Z3HE8tyOL8ALrHaIXGDlPw5/zNdUqlp5h+VxDggx/4EYoKosF5MfDgZCm03yzGATNQTHx25lTheUOM3Sw4I5ECrDSkRS8Bqt+nkbRFckHo69hK0OdOO7PSRH/MFhZ6STj32cBH1Ujc08qOrgzmrAucZZujS1dT5sA9f0p3V0scZeQxW+GH0MxFNoDmTIMl3kiu9XdZBvUgFvr2lkyuPwEaXRgEY+FW/DaCpAWI6iBfkNPQXApsbdtqIUzPaWNnWR3Y9ZrNqNCliueZdqXmr6GOiPqzJS8V82cgSxub0sqrJjqGdFYgVc5Zzx8SQ3pjGfBaMNLB8klwi1p3Xvb2MDS5LiILAnqqJ0ZgGF0ZFUB5LV7G3woXgzgFhRY2K7uj6YjDAzMsIxgnzSX1GLenAxkn00pVp03mE505OMoCgtv1Op11WYxeIsf9t7Ec="

cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt

before_cache:
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt        -name "*.lock"               -print -delete